# Generated by Django 5.0.6 on 2024-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='project',
            field=models.CharField(max_length=200),
        ),
    ]
